server.port=${PORT:8089}

# H2 메모리 DB 설정
spring.datasource.url=jdbc:h2:mem:./h2db/board_db;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 콘솔
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:~/test

# JPA (메모리 DB는 create 또는 update 추천)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true