# Render에서는 PORT 환경변수를 사용하고,
# 로컬에서는 PORT가 없으니 8089으로 실행
server.port=${PORT:8089}

# H2 파일 DB (자동 생성 옵션 AUTO_SERVER 및 DB 생성 허용 추가)
spring.datasource.url=jdbc:h2:file:./h2db/board_db;AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 콘솔
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true